const semesters = {
    FA2025: {
        ADY201m: { sections: {} },
        MAD101: { sections: {} },
        MAI301: { sections: {} }
    },

    SP2026: {
        CPV: {
            sections: {
                "Câu hỏi chuẩn bị": [
{ question: "What is computer vision?", answer: "Thị giác máy tính là một lĩnh vực khoa học máy tính, cho phép máy tính hiểu ảnh giống như một con người." },
{ question: "What is an image transformation?", answer: "Biến đổi ảnh là quá trình áp dụng một phép toán hoặc quy tắc lên ảnh đầu vào để tạo ra ảnh mới. Trong đó, giá trị pixel, hình dạng hoặc cách biểu diễn của ảnh bị thay đổi." },
{ question: "What does a geometric transformation involve?", answer: "Biến đổi hình học là phép biến đổi làm thay đổi vị trí, kích thước hoặc hình dạng của ảnh mà không thay đổi giá trị pixel gốc." },
{ question: "What are homogeneous coordinates used for?", answer: "Tọa độ đồng nhất được dùng để biểu diễn và tính toán các phép biến đổi hình học bằng phép nhân ma trận một cách thống nhất." },
{ question: "What is shearing in image transformation?", answer: "Biến dạng xiên là phép biến đổi hình học làm ảnh bị nghiêng/xiên. Trong đó một trục bị kéo theo trục còn lại." },
{ question: "What happens when light hits an object’s surface?", answer: "Khi ánh sáng chiếu vào bề mặt một vật thể, một phần bị phản xạ, một phần hấp thụ, có thể truyền qua hoặc tán xạ, tùy vào tính chất bề mặt vật thể." },
{ question: "What does Lambert's cosine law state?", answer: "Luật cosine Lambert : Cường độ ánh sáng phản xạ từ bề mặt tỉ lệ với cos(θ). Trong đó θ là góc giữa hướng ánh sáng tới và pháp tuyến bề mặt. θ = 0 => bề mặt sáng nhất. θ càng lớn thì bề mặt càng tối." },
{ question: "What is the thin lens model used for?", answer: "Mô hình thấu kính mỏng được dùng trong quang học để mô tả cách thấu kính tạo ra ảnh." },
{ question: "What causes chromatic aberration in lenses?", answer: "Quang sai xảy ra do sự tán sắc ánh sáng. Chiết suất của thủy tinh thay đổi nhẹ theo bước sóng. Do đó, các bước sóng khác nhau sẽ hội tụ tại những khoảng cách hơi khác nhau." },
{ question: "What are mipmaps in computer graphics?", answer: "Trong đồ họa máy tính, mipmaps là một chuỗi các ảnh đã được tính toán sẵn và tối ưu. Trong đó mỗi ảnh là một biểu diễn có độ phân giải thấp dần của ảnh trước đó." },

{ question: "What is digital image processing?", answer: "Xử lí ảnh số là sử dụng máy tính số để xử lí ảnh số thông qua các thuật toán." },
{ question: "What are camera parameters used for in digital imaging?", answer: "Các tham số camera là những tham số được sử dụng trong mô hình camera để mô tả mối quan hệ toán học giữa tọa độ 3D của một điểm trong cảnh (nơi ánh sáng phát ra) và tọa độ 2D của điểm đó khi được chiếu lên mặt phẳng ảnh." },
{ question: "What is a color space?", answer: "Không gian màu là cách tổ chức các màu sắc cụ thể." },
{ question: "How do we see color?", answer: "Để nhìn thấy màu sắc, chúng ta cần ánh sáng. Khi ánh sáng chiếu vào vật thể, một phần màu sắc được bật lại và một phần khác được hấp thụ. Mắt của chúng ta chỉ nhìn được các màu sắc được bật lại hoặc phản xạ lại." },
{ question: "What is histogram equalization used for?", answer: "Histogram equalization (Cân bằng lược đồ xám) là kỹ thuật xử lý ảnh dùng để phân bố lại mức xám nhằm tăng độ tương phản, đồng thời giúp chuẩn hóa ảnh để ít bị ảnh hưởng bởi thay đổi điều kiện chiếu sáng." },
{ question: "What is contrast stretching in image processing?", answer: "Dãn đối (contrast stretching, còn gọi là chuẩn hóa) nhằm cải thiện ảnh bằng cách dãn rộng dải giá trị cường độ mà ảnh đang có để tận dụng đầy đủ các giá trị có thể." },
{ question: "What is thresholding in image processing?", answer: "Thresholding (ngưỡng hóa) là kỹ thuật xử lý ảnh dùng một giá trị ngưỡng T để phân đoạn ảnh bằng cách gán mỗi pixel thành đen hoặc trắng tùy theo cường độ của nó nhỏ hơn hay lớn hơn T." },
{ question: "What is the difference between linear and non-linear filtering?", answer: "Linear filtering là phép lọc trong đó giá trị của pixel đầu ra là tổ hợp tuyến tính của các pixel trong vùng lân cận (thường thực hiện bằng tích chập). Non-linear filtering là phép lọc trong đó giá trị pixel đầu ra không phải tổ hợp tuyến tính, mà được xác định bằng các phép toán như sắp xếp hoặc chọn các pixel lân cận (ví dụ: median filter)." },
{ question: "What is a mean filter?", answer: "Bộ lọc trung bình (mean filter) thay thế mỗi giá trị pixel bằng giá trị trung bình của các pixel trong vùng lân cận của nó, bao gồm cả chính pixel đó." },
{ question: "What is convolution in image processing?", answer: "Convolution (tích chập) là phép toán trong xử lý ảnh, trong đó một kernel (mặt nạ) được trượt trên ảnh để tính giá trị pixel đầu ra bằng tổng có trọng số của các pixel lân cận." },

{ question: "What is correlation in image processing?", answer: "Correlation (Tương quan ) là toán tử cục bộ trong xử lý ảnh, dùng để đo mức độ tương đồng giữa một kernel (mặt nạ) và các vùng cục bộ của ảnh bằng cách trượt kernel trên ảnh mà không lật nó." },
{ question: "What is Gaussian smoothing?", answer: "Gaussian smoothing (làm mượt Gaussian) là kỹ thuật làm mờ ảnh bằng cách lấy trung bình có trọng số các pixel xung quanh, trong đó pixel gần trung tâm được ưu tiên hơn theo phân bố Gaussian (chuông). Mục đích chính: giảm nhiễu (noise), làm ảnh mượt hơn trước khi xử lý tiếp (Canny, Harris, Hough…)." },
{ question: "What is the Fourier Transform used for in image processing?", answer: "Biến đổi Fourier là một công cụ quan trọng trong xử lý ảnh, dùng để chuyển ảnh từ miền không gian sang miền tần số bằng cách phân rã ảnh thành các thành phần sin và cos." },
{ question: "What are the properties of the Fourier Transform?", answer: "1. Superposition (Tính chồng chập / tuyến tính) 2. Shift (Tính dịch chuyển) 3. Reversal (Tính đảo ngược) 4. Convolution (Tính chập) 5. Correlation (Tương quan) 6. Multiplication (Nhân) 7. Differentiation (Đạo hàm) 8. Domain scaling (Co giãn miền) 9. Real images (Ảnh thực) 10. Định lý Parseval (Bảo toàn năng lượng)" },
{ question: "What is an elliptical weighted average (EWA)?", answer: "Trung bình trọng số elip (Elliptical Weighted Average – EWA) là phương pháp nội suy và lọc ảnh trong xử lý ảnh, trong đó giá trị của một điểm ảnh mới được tính bằng trung bình có trọng số các điểm ảnh lân cận nằm trong một vùng hình elip trên ảnh gốc. " },
{ question: "What is anisotropic filtering used for?", answer: "Anisotropic filtering là một phương pháp cải thiện chất lượng hình ảnh của các texture trên bề mặt trong đồ họa máy tính, đặc biệt khi các bề mặt này được nhìn ở góc xiên so với camera, nơi texture bị chiếu (projection) theo một hướng nghiêng." },
{ question: "What are feature detectors in image processing?", answer: "Đây là một thuật toán phát hiện đặc trưng trong thị giác máy tính, dùng để phát hiện và mô tả các đặc trưng cục bộ trong ảnh." },
{ question: "What is a feature descriptor?", answer: "Feature descriptor là một thuật toán nhận đầu vào là một ảnh và xuất ra các mô tả đặc trưng (feature descriptors) hoặc các vector đặc trưng (feature vectors)." },
{ question: "What is feature matching?", answer: "Ghép nối đặc trưng là quá trình so sánh và tìm các cặp đặc trưng tương ứng giữa hai hoặc nhiều ảnh dựa trên các mô tả đặc trưng của chúng." },
{ question: "What are the two types of edge detection?", answer: "Hai loại phát hiện biên (Edge Detection): Toán tử dựa trên Gradient: tính đạo hàm bậc nhất của ảnh số, ví dụ như Sobel, Prewitt, Robert. Toán tử dựa trên Gaussian: tính đạo hàm bậc hai của ảnh số, ví dụ như Canny edge detector, Laplacian of Gaussian." },

{ question: "What is the gradient in image processing?", answer: "Gradient trong xử lý ảnh là vector biểu diễn sự thay đổi cường độ sáng theo không gian, được tính bằng đạo hàm bậc nhất theo x và y. Độ lớn của gradient cho biết mức thay đổi mạnh hay yếu, còn hướng của gradient cho biết hướng thay đổi đó." },
{ question: "What does the Sobel operator do?", answer: "Nó tính xấp xỉ gradient của hàm cường độ ảnh để phát hiện biên. Tại mỗi pixel, toán tử Sobel tạo ra vector gradient (hoặc vector pháp tuyến tương ứng). Sobel sử dụng hai kernel 3×3, được tích chập với ảnh đầu vào để tính xấp xỉ đạo hàm theo phương ngang và phương dọc." },
{ question: "What does the Prewitt operator detect?", answer: "Nó phát hiện các cạnh theo phương ngang và phương dọc trong ảnh. Đây là một trong những phương pháp dùng để xác định hướng (orientation) và độ lớn (magnitude) của cạnh trong ảnh." },
{ question: "What is the Laplacian of Gaussian used for?", answer: "Đây là toán tử dựa trên Gaussian, sử dụng Laplacian để tính đạo hàm bậc hai của ảnh. Hoạt động tốt khi sự chuyển mức xám diễn ra đột ngột. Nó dựa trên phương pháp zero-crossing, tức là khi đạo hàm bậc hai đổi dấu (cắt qua 0) thì vị trí đó tương ứng với một biên. Gaussian giúp giảm nhiễu trước, còn Laplacian dùng để phát hiện các cạnh sắc nét." },
{ question: "What is the Canny Operator?", answer: "Đây là toán tử phát hiện biên dựa trên Gaussian. Ít nhạy với nhiễu nhờ bước làm trơn bằng Gaussian. Trích xuất đặc trưng biên mà không làm biến dạng đáng kể biên. Là thuật toán nâng cao, phát triển sau các phương pháp như Laplacian of Gaussian. Được sử dụng rộng rãi và được xem là một trong những kỹ thuật phát hiện biên tối ưu." },
{ question: "What is image segmentation?", answer: "Segmentation (Phân đoạn ảnh) là quá trình chia ảnh thành các vùng khác nhau dựa trên đặc trưng của pixel (như màu sắc, cường độ, kết cấu) để xác định đối tượng hoặc ranh giới. Mục tiêu là đơn giản hóa và thay đổi cách biểu diễn ảnh thành dạng có ý nghĩa hơn và dễ phân tích hơn. Trong phân đoạn ảnh, mỗi pixel được gán một nhãn sao cho các pixel cùng nhãn có chung đặc điểm. Kết quả của phân đoạn ảnh là một tập các vùng (segments) bao phủ toàn bộ ảnh, hoặc một tập các đường bao (contours) được trích xuất từ ảnh." },
{ question: "What is the purpose of edge-based segmentation?", answer: "Mục đích của edge-based segmentation là xác định và sử dụng các cạnh (biên) trong ảnh để phân tách các đối tượng hoặc vùng khác nhau." },
{ question: "What is thresholding in image segmentation?", answer: "Thresholding là phương pháp phân đoạn ảnh bằng cách so sánh giá trị pixel với một ngưỡng (threshold) để tách ảnh thành các vùng, thường là tách đối tượng khỏi nền." },
{ question: "Why is image segmentation important for cancer detection?", answer: "Phân đoạn ảnh quan trọng trong phát hiện ung thư vì nó tách vùng khối u ra khỏi mô khỏe mạnh, giúp xác định chính xác vị trí, kích thước và phân tích vùng nghi ngờ." },
{ question: "What is semantic segmentation?", answer: "Semantic segmentation là một phương pháp xác định, với mỗi pixel trong ảnh, nó thuộc về lớp (nhóm) nào của đối tượng." },

{ question: "What is instance segmentation?", answer: "Instance segmentation là một phương pháp xác định, với mỗi pixel trong ảnh, nó thuộc về một cá thể (instance) cụ thể của đối tượng. Phương pháp này phát hiện từng đối tượng riêng biệt trong ảnh." },
{ question: "What are active contours?", answer: "Active contour là một kỹ thuật phân đoạn ảnh sử dụng các lực năng lượng và các ràng buộc để tách các pixel thuộc vùng quan tâm ra khỏi ảnh." },
{ question: "What are key factors in facial feature analysis?", answer: "Key factors in facial feature analysis là khoảng cách giữa hai mắt, độ sâu của hốc mắt, khoảng cách từ trán đến cằm, hình dạng xương gò má và đường viền của môi, tai và cằm." },
{ question: "What is the Scale-Invariant Feature Transform (SIFT)?", answer: "Là một thuật toán phát hiện đặc trưng trong thị giác máy tính, dùng để phát hiện và mô tả các đặc trưng cục bộ trong ảnh." },
{ question: "Why is a single threshold rarely sufficient for image thresholding?", answer: "Threshold: một ngưỡng đơn lẻ hiếm khi đủ cho toàn bộ ảnh do sự thay đổi về ánh sáng và sự biến thiên thống kê bên trong cùng một đối tượng." },
{ question: "What is split and merge segmentation?", answer: "Split and merge segmentation là phương pháp phân đoạn ảnh dựa trên tiêu chí đồng nhất, trong đó ảnh được chia thành các vùng nhỏ, sau đó kiểm tra độ đồng nhất của từng vùng và các vùng thỏa điều kiện sẽ được gộp với các vùng lân cận, quá trình này lặp lại cho đến khi tất cả các vùng đều đạt tiêu chí đồng nhất." },
{ question: "What is the watershed transformation?", answer: "Watershed transformation là một phương pháp phân đoạn ảnh áp dụng trên ảnh mức xám, trong đó ảnh được xem như một bề mặt địa hình với độ sáng biểu thị độ cao. Thuật toán mô phỏng quá trình nước dâng lên từ các thung lũng và xây “đập” tại nơi các vùng nước gặp nhau, các đường đập này chính là ranh giới giữa các vùng hay các đối tượng trong ảnh." },
{ question: "What is region splitting in image processing?", answer: "Region splitting trong xử lý ảnh là phương pháp phân đoạn trong đó ảnh ban đầu được xem như một vùng duy nhất, sau đó kiểm tra xem vùng đó có thỏa điều kiện đồng nhất hay không; nếu không thỏa, vùng sẽ được chia nhỏ (thường thành bốn vùng con) và quá trình lặp lại cho đến khi tất cả các vùng đều thỏa điều kiện đồng nhất hoặc không thể chia nhỏ thêm nữa." },
{ question: "What is a Gaussian Mixture Model (GMM)?", answer: "Gaussian Mixture Model (GMM) là một mô hình xác suất giả định rằng dữ liệu được tạo ra từ nhiều phân phối Gaussian khác nhau, trong đó mỗi phân phối đại diện cho một cụm. Mỗi cụm được đặc trưng bởi một giá trị trung bình và phương sai riêng, và một điểm dữ liệu có thể thuộc về nhiều cụm với các xác suất khác nhau (phân cụm mềm)." },
{ question: "What does K-means clustering do?", answer: "K-means clustering dùng để phân nhóm dữ liệu thành K cụm dựa trên mức độ tương đồng, sao cho các điểm trong cùng một cụm giống nhau hơn so với các điểm ở cụm khác." },

{ question: "What is feature-based alignment?", answer: "Feature-based alignment là phương pháp căn chỉnh hai hoặc nhiều ảnh bằng cách trích xuất các đặc trưng (keypoints) từ mỗi ảnh, sau đó so khớp các đặc trưng tương ứng giữa các ảnh và ước lượng một phép biến đổi hình học như tịnh tiến, quay, affine hoặc homography dựa trên các cặp điểm đã khớp, nhằm biến đổi một ảnh sao cho khớp hình học với ảnh còn lại." },
{ question: "What is RANSAC used for?", answer: "RANSAC được dùng để ước lượng tham số của một mô hình trong dữ liệu có nhiều điểm ngoại lai (outliers). Nó hoạt động bằng cách chọn ngẫu nhiên các tập con nhỏ dữ liệu để tạo mô hình ứng viên, sau đó kiểm tra mô hình nào có nhiều điểm phù hợp (inliers) nhất và chọn mô hình đó làm kết quả cuối cùng." },
{ question: "What is image stitching?", answer: "Image stitching là quá trình kết hợp nhiều ảnh có vùng chồng lấp với nhau để tạo thành một ảnh lớn hơn, như ảnh panorama hoặc ảnh có độ phân giải cao, bằng cách căn chỉnh và ghép các ảnh sao cho chúng khớp hình học với nhau." },
{ question: "What is bundle adjustment in image stitching?", answer: "Bundle adjustment trong image stitching là quá trình tối ưu đồng thời các tham số pose (vị trí và hướng) của nhiều ảnh chồng lấp nhau bằng cách giảm tổng sai số giữa các điểm đặc trưng đã khớp. Mục tiêu là điều chỉnh toàn bộ tập ảnh cùng lúc để đạt căn chỉnh toàn cục tốt nhất, thay vì chỉ căn chỉnh từng cặp ảnh riêng lẻ." },
{ question: "What is parallax and why is it important to remove it in imaging?", answer: "Parallax là hiện tượng một vật thể có vẻ thay đổi vị trí khi được quan sát từ hai góc nhìn khác nhau, do sự khác biệt về vị trí giữa các điểm quan sát. Trong xử lý ảnh, đặc biệt là ghép ảnh hoặc tạo panorama, parallax gây ra sai lệch hình học giữa các vùng chồng lấp, làm xuất hiện bóng mờ, lệch mép hoặc méo hình. Vì vậy, cần loại bỏ hoặc hiệu chỉnh parallax để các ảnh căn chỉnh chính xác và tạo ra kết quả liền mạch, tự nhiên." },
{ question: "What is the task of object detection?", answer: "Nhiệm vụ của object detection là phát hiện và định vị các đối tượng thuộc một lớp nhất định trong ảnh hoặc video, thường bằng cách xác định nhãn lớp và vẽ bounding box bao quanh từng đối tượng." },
{ question: "What are Histogram of Oriented Gradients used for?", answer: "Histogram of Oriented Gradients (HOG) được dùng để trích xuất đặc trưng hình dạng từ ảnh bằng cách mô tả phân bố hướng của gradient. Chúng thường được sử dụng trong các bài toán phát hiện đối tượng, đặc biệt là phát hiện khuôn mặt và người, vì HOG nắm bắt tốt các cạnh và cấu trúc hình học đặc trưng của đối tượng." },
{ question: "What is the purpose of face analysis?", answer: "Mục tiêu là xác định các mốc đặc trưng trên khuôn mặt dùng để phân biệt khuôn mặt của bạn." },
{ question: "What is the task of object tracking?", answer: "Object tracking là nhiệm vụ bắt đầu từ một tập các đối tượng đã được phát hiện ban đầu, gán cho mỗi đối tượng một ID duy nhất, sau đó theo dõi các đối tượng này khi chúng di chuyển qua các khung hình trong video, đồng thời duy trì đúng ID đã gán cho từng đối tượng." },
{ question: "Describe the steps in the Canny edge detection algorithm.", answer: "Canny edge detection gồm: khử nhiễu bằng Gaussian, tính độ lớn và hướng gradient, làm mảnh biên bằng non-maximum suppression, rồi dùng double threshold và hysteresis để giữ biên mạnh và loại biên yếu không liên thông." },

{ question: "Describe the steps in image stitching.", answer: "Image stitching gồm: phát hiện đặc trưng, ghép cặp điểm tương ứng giữa các ảnh, ước lượng phép biến đổi (homography), biến đổi và căn chỉnh ảnh, sau đó blend các ảnh lại để tạo ảnh toàn cảnh mượt và liền mạch." },
{ question: "Describe the steps in Feature-Based Alignment.", answer: "Feature-Based Alignment gồm các bước: phát hiện và trích xuất đặc trưng (keypoints và descriptors) từ các ảnh, so khớp các đặc trưng tương ứng giữa các ảnh, loại bỏ outliers (thường dùng RANSAC), ước lượng phép biến đổi hình học phù hợp (như affine hoặc homography), rồi biến đổi (warp) một ảnh để căn chỉnh khớp với ảnh còn lại." },
{ question: "Describe the steps in K-means algorithm for image segmentation.", answer: "K-means cho phân đoạn ảnh gồm các bước: chọn số cụm K, khởi tạo ngẫu nhiên K tâm cụm, gán mỗi pixel vào cụm có tâm gần nhất (thường theo khoảng cách Euclidean trong không gian màu), cập nhật lại tâm cụm bằng trung bình các pixel trong cụm, lặp lại hai bước gán và cập nhật cho đến khi các tâm cụm hội tụ hoặc không còn thay đổi đáng kể." },
{ question: "Describe the process of face detection using Histogram of Oriented Gradients.", answer: "Quá trình phát hiện khuôn mặt bằng Histogram of Oriented Gradients (HOG) gồm: trước hết tính gradient theo cả hai hướng và lấy độ lớn cùng hướng gradient cho từng pixel, sau đó chia ảnh thành các ô nhỏ (cells) và xây dựng histogram hướng gradient cho mỗi ô, chuẩn hóa các histogram theo từng block để giảm ảnh hưởng của ánh sáng, tạo vector đặc trưng HOG cho từng vùng cửa sổ, tiếp theo dùng cửa sổ trượt ở nhiều tỉ lệ khác nhau để quét toàn ảnh, và cuối cùng đưa vector đặc trưng vào bộ phân loại (thường là SVM) để quyết định vùng đó có phải khuôn mặt hay không." },
{ question: "Describe the process of detecting lines using the Hough transform.", answer: "Quá trình phát hiện đường thẳng bằng Hough transform gồm: trước hết phát hiện các điểm biên trong ảnh (thường dùng Canny), sau đó biểu diễn mỗi điểm biên trong không gian tham số (ρ, θ) theo phương trình đường thẳng ρ = xcosθ + ysinθ, cho mỗi điểm biên bỏ phiếu (vote) vào các cặp (ρ, θ) có thể tạo thành đường đi qua điểm đó, tích lũy số phiếu trong ma trận accumulator, rồi tìm các đỉnh (peaks) trong không gian tham số; mỗi đỉnh tương ứng với một đường thẳng trong ảnh gốc." }

],

                "Bài tập tự luyện": [
                    // Sau này bạn thêm bài tập vào đây
                ]
            }
        },

        DAP: { sections: {} },
        SSG: { sections: {} },
        AIL: { sections: {} },
        SWE: { sections: {} }
    }
};